// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-RjUL9rHbu5-ZplTs0_3HahtV6eC5DmM',
    appId: '1:443168020544:android:d567c4347d2e71104367a5',
    messagingSenderId: '443168020544',
    projectId: 'skynet-2eb58',
    storageBucket: 'skynet-2eb58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgZe8pBL4liTQrOQUMiIGENjOTH8z9YNE',
    appId: '1:443168020544:ios:693809e6bc3c2c204367a5',
    messagingSenderId: '443168020544',
    projectId: 'skynet-2eb58',
    storageBucket: 'skynet-2eb58.appspot.com',
    iosBundleId: 'com.example.skynet',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjUuQh4CF-MUdX8QCdQYXgm_rofvPPZuw',
    appId: '1:443168020544:web:65b453902d3ec25b4367a5',
    messagingSenderId: '443168020544',
    projectId: 'skynet-2eb58',
    authDomain: 'skynet-2eb58.firebaseapp.com',
    storageBucket: 'skynet-2eb58.appspot.com',
    measurementId: 'G-DM75G5FPB4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjUuQh4CF-MUdX8QCdQYXgm_rofvPPZuw',
    appId: '1:443168020544:web:a9e97e4fcb22dd8e4367a5',
    messagingSenderId: '443168020544',
    projectId: 'skynet-2eb58',
    authDomain: 'skynet-2eb58.firebaseapp.com',
    storageBucket: 'skynet-2eb58.appspot.com',
    measurementId: 'G-10T1J4BY2C',
  );

}